name: Codespace  # A descriptive name for the GitHub workflow

on: [push]  # Specifies that this workflow will be triggered when changes are pushed to the repository

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies that this job will run on the latest version of Ubuntu

    steps:
    - uses: actions/checkout@v2  # Checks out the repository's code into the runner's working directory

    - name: Set up Python 3.8  # A descriptive name for this step
      uses: actions/setup-python@v1  # Uses a pre-built action to set up Python 3.8
      with:
        python-version: 3.8  # Specifies the version of Python to set up

    - name: Install dependencies  # A descriptive name for this step
      run: |  # Runs the following commands as shell commands
        make install  # Installs the dependencies specified in the Makefile
